---
name: Amendment
description: Amend the Aragon Network Charter
title: "[Amendment]: "
labels: ["enhancement"]
assignees:
  - Michael-A-Heuer
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to make an amendment!
  - type: dropdown
    id: where
    attributes:
      label: In which part?
      description: In which part of the document would you like to make an amendment?
      options:
        - Introduction to the Charter
        - Aragon Network DAO Agreement
        - Aragon Manifesto
        - Community-Guidelines
        - Aragon Governance Proposal Process
        - Sub-DAO Agreements
        - Main DAO and Sub-DAO Parameters
        - Multiple parts
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: 
        What should be changed?
      description: 
        What would you like to change (and how should it be formatted)?
        Please, specify the line number or paragraph.
      placeholder: 
        "
        - Part 3, line 75: Add sentence 'XYZ'.\n
        - Part 4, line 20-23: 'Remove 'ABC'.\n
        - Part 6, paragraph 3.a.i.1: 'Replace '123' by '456'.
        "
    validations:
      required: true
---
