name: 'Test the Aragon Network DAO Charter'

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Tectonic Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/Tectonic
          key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
          restore-keys: |
           ${{ runner.os }}-tectonic-
     
      - name: Tectonic Setup
        uses: wtfjoke/setup-tectonic@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create Gitinfo
        run: ./gitinfo.sh

      - name: Build sub pages
        run: |
          for f in $(find . -regex '\.\/[1-8]-.+\.tex'); do 
            tectonic -r 1 $f 
          done 

      - name: Build charter
        run: tectonic -r 1 network-dao-charter.tex
